title: Caroline Parins-Fukuchi
email: cfukuchi@umich.edu
description: Computational Paleobiology and Evolution
twitter_username: carolinetomo
github_username: carolinetomo

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - projects.md
  - papers.md
  - software.md
