#theme: jekyll-theme-slate
title: Caroline Parins-Fukuchi
email: cfukuchi@umich.edu
description: Computational Evolutionary Biologist
twitter_username: carolinetomo
github_username: carolinetomo

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
        - projects.md
        - papers.md
        - software.md
