title: Dr. Caroline Parins-Fukuchi
email: parinsfukuchi@uchicago.edu
description: Computational Paleobiology and Macroevolution
twitter_username: carolinetomo
github_username: carolinetomo

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - projects.md
  - papers.md
  - software.md
